//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condai.Entity.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguridad_RolesPorUsuario
    {
        public int rpuId { get; set; }
        public int usuId { get; set; }
        public int rouId { get; set; }
        public int usuIdCreo { get; set; }
        public System.DateTime usuFechaCreo { get; set; }
        public int usuIdActualizo { get; set; }
        public System.DateTime usuFechaActualizo { get; set; }
    
        public virtual Seguridad_Rol Seguridad_Rol { get; set; }
    }
}
