//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condai.Entity.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguridad_Usuario
    {
        public int usuId { get; set; }
        public string usuUsuario { get; set; }
        public string usuDescripcion { get; set; }
        public string usuClave { get; set; }
        public string usuNombre { get; set; }
        public string usuApellido { get; set; }
        public string usuCorreo { get; set; }
        public long usuTelefono { get; set; }
        public bool usuActivo { get; set; }
        public System.DateTime usuFechaUltimoIngreso { get; set; }
        public int usuIdCreo { get; set; }
        public System.DateTime usuFechaCreo { get; set; }
        public int usuIdActualizo { get; set; }
        public System.DateTime usuFechaActualizo { get; set; }
    }
}
