//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condai.Entity.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_Pais
    {
        public Base_Pais()
        {
            this.Base_Departamento = new HashSet<Base_Departamento>();
        }
    
        public int paiId { get; set; }
        public string paiNombre { get; set; }
        public string paiDescripcion { get; set; }
        public string paiCodigoDane { get; set; }
        public int usuIdCreo { get; set; }
        public System.DateTime usuFechaCreo { get; set; }
        public int usuIdActualizo { get; set; }
        public System.DateTime usuFechaActualizo { get; set; }
    
        public virtual ICollection<Base_Departamento> Base_Departamento { get; set; }
    }
}
