//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condai.Entity.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_Empresa
    {
        public int empId { get; set; }
        public string parIdTCO { get; set; }
        public string parValorTCO { get; set; }
        public string empCodigo { get; set; }
        public string empRazonSocial { get; set; }
        public string empDireccion { get; set; }
        public string empTelefono { get; set; }
        public string empCorreo { get; set; }
        public bool empActivo { get; set; }
        public int usuIdCreo { get; set; }
        public System.DateTime usuFechaCreo { get; set; }
        public int usuIdActualizo { get; set; }
        public System.DateTime usuFechaActualizo { get; set; }
    
        public virtual Base_Parametro Base_Parametro { get; set; }
    }
}
