//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condai.Entity.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_ParametroDescripcion
    {
        public Base_ParametroDescripcion()
        {
            this.Base_Parametro = new HashSet<Base_Parametro>();
        }
    
        public string parId { get; set; }
        public string parDescripcion { get; set; }
    
        public virtual ICollection<Base_Parametro> Base_Parametro { get; set; }
    }
}
