//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condai.Entity.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_Parametro
    {
        public Base_Parametro()
        {
            this.Base_Cliente = new HashSet<Base_Cliente>();
            this.Base_Empresa = new HashSet<Base_Empresa>();
            this.Base_ParametroCascada = new HashSet<Base_ParametroCascada>();
            this.Base_ParametroCascada1 = new HashSet<Base_ParametroCascada>();
        }
    
        public string parId { get; set; }
        public string parValor { get; set; }
        public string parDescripcion { get; set; }
    
        public virtual ICollection<Base_Cliente> Base_Cliente { get; set; }
        public virtual ICollection<Base_Empresa> Base_Empresa { get; set; }
        public virtual Base_ParametroDescripcion Base_ParametroDescripcion { get; set; }
        public virtual ICollection<Base_ParametroCascada> Base_ParametroCascada { get; set; }
        public virtual ICollection<Base_ParametroCascada> Base_ParametroCascada1 { get; set; }
    }
}
