//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condai.Entity.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_Menu
    {
        public int menId { get; set; }
        public string menIcono { get; set; }
        public string menNombre { get; set; }
        public string menDireccion { get; set; }
        public bool menActivo { get; set; }
        public int menOrden { get; set; }
    }
}
