//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condai.Entity.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_ParametroCascada
    {
        public int pacId { get; set; }
        public string parId1 { get; set; }
        public string parValor1 { get; set; }
        public string parId2 { get; set; }
        public string parValor2 { get; set; }
        public int cliId { get; set; }
        public Nullable<int> empId { get; set; }
        public string pacDescripcion { get; set; }
    
        public virtual Base_Parametro Base_Parametro { get; set; }
        public virtual Base_Parametro Base_Parametro1 { get; set; }
    }
}
