//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condai.Entity.Contacto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto_Inquietud
    {
        public int id { get; set; }
        public string NombreApellido { get; set; }
        public string Ocupacion { get; set; }
        public string Pais { get; set; }
        public long Telefono { get; set; }
        public string Correo { get; set; }
        public string Duda { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    }
}
