//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condai.DAL.Modelo
{
    using Entity;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Condai.Entity.Base;

    public partial class CondaiBase : DbContext
    {
        public CondaiBase()
            : base("name=CondaiBase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Base_Aplicacion> Base_Aplicacion { get; set; }
        public virtual DbSet<Base_Departamento> Base_Departamento { get; set; }
        public virtual DbSet<Base_Municipio> Base_Municipio { get; set; }
        public virtual DbSet<Base_Pais> Base_Pais { get; set; }
        public virtual DbSet<Base_Menu> Base_Menu { get; set; }
        public virtual DbSet<Base_Cliente> Base_Cliente { get; set; }
        public virtual DbSet<Base_Empresa> Base_Empresa { get; set; }
        public virtual DbSet<Base_Parametro> Base_Parametro { get; set; }
        public virtual DbSet<Base_ParametroCascada> Base_ParametroCascada { get; set; }
        public virtual DbSet<Base_ParametroDescripcion> Base_ParametroDescripcion { get; set; }
    }
}
